os: osx
osx_image: xcode9.3
language: swift

before_install:
  - gem install xcpretty

script:
  - xcodebuild clean build -sdk iphonesimulator11.3 -workspace sight.xcworkspace -scheme sight CODE_SIGNING_REQUIRED=NO | xcpretty
